services:
  - type: web
    name: esp32-c3-alarm-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DEVICE_TOKEN
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
